bb2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),

]

core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.main_page, name='main_page'),
    url(r'^core/create-user/$', views.create_user_view, name='create_user'),
    url(r'^core/login-user/$', views.login_user_view, name='login_user'),
    url(r'^core/edit-user-profile/(?P<pk>\d+)/$', views.edit_user_profile, name='edit_user_profile'),
    url(r'^core/edit-user-password/$', views.edit_user_password, name='edit_user_password'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from django.contrib.auth.models import User


class UserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, **fields):

        fields['email'] = fields['username']

        date_joined = fields.pop('date_joined', None) or timezone.now()
        password = fields.pop('password')
        user = self.model(is_superuser=False, date_joined=date_joined, **fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password):
        if not username:
            raise ValueError('The given username must be set')

        now = timezone.now()

        user = self.model(username=username, email=username, is_staff=True, is_active=True,
                          is_superuser=True, date_joined=now, is_admin=True)
        user.set_password(password)
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.EmailField('email', unique=True)
    email = models.EmailField('email address', max_length=255, unique=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField('Дата регистрации')

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

core/forms.py
from django.contrib.auth.models import User
from django import forms
from .import models
from .models import MyUser


class CreateUser(forms.Form):
    username = forms.CharField(label='Пользователь',
                               max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль',
                                max_length=50,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Подтвердите пароль',
                                max_length=50,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.CharField(label='Адрес электронной почты',
                            max_length=50,
                            required=True,
                            widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = super().clean()
        passwd_1 = cleaned_data.get('password1')
        passwd_2 = cleaned_data.get('password2')

        if passwd_1 and passwd_2 and passwd_1 != passwd_2:
            self.add_error('password1', 'Пароли не совпадают')
            self.add_error('password2', 'Пароли не совпадают')

        return cleaned_data


class CreateLogin(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = '__all__'

core/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User


def main_page(request):

    return render(request, 'main_page.html')


def create_user_view(request):
    form = forms.CreateUser(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['username'],
                                            password=form.cleaned_data['password1'],
                                            email=form.cleaned_data['email'])
            user.save()
            return redirect('core:create_user')

    return render(request, 'create_user_form.html', locals())


def login_user_view(request):
    login_form = forms.CreateLogin(request.POST or None)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)

            return redirect('core:main_page')

    return render(request, 'login_user_form.html', locals())


def edit_user_profile(request, pk):
    user_profile = models.MyUser.objects.get(id=pk)

    return render(request, 'edit_user_profile.html', locals())


def edit_user_password(request):

    return render(request, 'edit_user_password.html', locals())

templates/create_user_form.html
{% extends 'layout.html' %}

{% block content %}

    <form class="form-horizontal" method="post" novalidate="novalidate">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-lg-2 col-md-2 col-sm-4">
                {{ form.username.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.username }}
                {% if form.username.errors %}
                    {{ form.username.errors }}
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2 col-md-2 col-sm-4">
                {{ form.password1.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.password1 }}
                {% if form.password1.errors %}
                    {{ form.password1.errors }}
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2 col-md-2 col-sm-4">
                {{ form.password2.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.password2 }}
                {% if form.password2.errors %}
                    {{ form.password2.errors }}
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2 col-md-2 col-sm-4">
                {{ form.email.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.email }}
                {% if form.email.errors %}
                    {{ form.email.errors }}
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Зарегистрировать</button>
            </div>
        </div>

    </form>
{% endblock %}

templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bb2</title>

    <link href="{% static 'dist/css/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'dist/js/bootstrap.js' %}"></script>

</head>
<body>
    <div class="container-fluid">

        <div class="row">
            <div class="col-lg-12">
                <div class="page-header">
                    <a href="{% url 'core:main_page' %}" class="btn btn-success">Главная</a>
                    {% if user.is_authenticated %}
                        Пользователь: {{ user.username }}
                    {% else %}
{#                        <a href="{% url 'core:login_user' %}" class="btn btn-success">Войти</a>#}
                        <a href="{% url 'core:login_user' %}" class="btn btn-primary">Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>

        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/login_user_form.html
{% extends 'layout.html' %}

{% block content %}

    <form class="form-horizontal" method="post" novalidate="novalidate">
        {% csrf_token %}

        <div class="form-group">
            <div class="col-lg-1 col-md-1 col-sm-2">
                {{ login_form.username.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ login_form.username }}
                {% if login_form.username.errors %}
                    {{ login_form.username.errors }}
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-1 col-md-1 col-sm-2">
                {{ login_form.password.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ login_form.password }}
                {% if login_form.password.errors %}
                    {{ login_form.password.errors }}
                {% endif %}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-2">
                <button type="submit" class="btn btn-primary">OK</button>
                <a href="{% url 'core:main_page' %}" class="btn btn-default">
                    <span>Выход</span>
                </a>
            </div>
        </div>

    </form>

{% endblock %}

templates/main_page.html
{% extends 'layout.html' %}

{% block content %}

    <h3 class="text-danger">Главная страница</h3>

    <form class="form-horizontal" method="post" novalidate="novalidate">
        {% csrf_token %}
{##}
{#        <div class="form-group">#}
{#            <div class="col-sm-offset-2 col-sm-10">#}
{#                <button type="submit" class="btn btn-primary">Зарегистрировать</button>#}
{#            </div>#}
{#        </div>#}
    </form>

{% endblock %}